### ISSUE TITLE
Increasing and decreasing identation of lines by pressing buttons

### ISSUE THREAD

**Issue by MarilinMat** [karljaats/atom-ui-beyondQL#25]
Increasing and decreasing identation of lines by pressing buttons "tab" or "tab" +"shift" buttons.

Use cases: https://github.com/dot-p-ketita/atom-ui-beyondQL/wiki/Use-Cases#uc-2
https://github.com/dot-p-ketita/atom-ui-beyondQL/wiki/Use-Cases#uc-3

Estimation: 2h

**Comment by karljaats** [comment]
Currently works by increasing/decreasing by 2 spaces but it needs to be 4 spaces.
