### ISSUE TITLE
Add missing Beyond syntax to the language grammar

### ISSUE THREAD

**Issue by klehes** [karljaats/atom-ui-beyondQL#6]
Add missing Beyond syntax to the language grammar.

Documentation:
https://github.com/karljaats/atom-ui-beyondQL/wiki/Syntax-Definition
https://github.com/karljaats/atom-ui-beyondQL/wiki/Advanced-Beyond-Syntax-Details

Estimation: 15h

**Comment by MarilinMat** [comment]
Managed to clean only the language grammar code from unused java functionalities.
